schema {
  mutation: RootMutationType
  query: RootQueryType
}

type RegisterWithPasswordMetadata {
  "A JWT that can be used to authenticate the user."
  token: String!
}

"The result of the :register_with_password mutation"
type RegisterWithPasswordResult {
  "The successful result of the mutation"
  result: User

  "Any errors generated, if the mutation failed"
  errors: [MutationError!]!

  "Metadata produced by the mutation"
  metadata: RegisterWithPasswordMetadata
}

input RegisterWithPasswordInput {
  email: String!

  "The proposed password for the user, in plain text."
  password: String!

  "The proposed password for the user (again), in plain text."
  passwordConfirmation: String!
}

input UserFilterEmail {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  contains: String
  isDistinctFrom: String
  isNotDistinctFrom: String
  rangeAdjacent: String
  rangeContains: String
  rangeOverlaps: String
  stringEndsWith: String
  stringStartsWith: String
}

input UserFilterId {
  isNil: Boolean
  eq: ID
  notEq: ID
  in: [ID!]
  lessThan: ID
  greaterThan: ID
  lessThanOrEqual: ID
  greaterThanOrEqual: ID
  isDistinctFrom: ID
  isNotDistinctFrom: ID
  rangeAdjacent: ID
  rangeContains: String
  rangeOverlaps: ID
}

input UserFilterInput {
  and: [UserFilterInput!]
  or: [UserFilterInput!]
  not: [UserFilterInput!]
  id: UserFilterId
  email: UserFilterEmail
}

type UserWithToken {
  id: ID!

  email: String!

  "A JWT that can be used to authenticate the user."
  token: String!
}

type User {
  id: ID!
  email: String!
}

"An error generated by a failed mutation"
type MutationError {
  "The human readable error message"
  message: String

  "A shorter error message, with vars not replaced"
  shortMessage: String

  "Replacements for the short message"
  vars: Json

  "An error code for the given error"
  code: String

  "The field or fields that produced the error"
  fields: [String!]

  "The path to the field that produced the error"
  path: [String!]
}

type RootQueryType {
  "The user identified by the request's bearer token, if any."
  currentUser(
    "A filter to limit the results"
    filter: UserFilterInput
  ): User
}

type RootMutationType {
  "Register a new user with a email and password."
  registerWithPassword(input: RegisterWithPasswordInput!): RegisterWithPasswordResult!

  "Attempt to sign in using a email and password."
  signInWithPassword(
    "A filter to limit the results"
    filter: UserFilterInput

    "The email to use for retrieving the user."
    email: String!

    "The password to check for the matching user."
    password: String!
  ): UserWithToken!
}

"""
The `Json` scalar type represents arbitrary json string data, represented as UTF-8
character sequences. The Json type is most often used to represent a free-form
human-readable json string.
"""
scalar Json
