defmodule WerewolfAsh.Repo.Migrations.AddGamesDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:actions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:type, :text, null: false)
      add(:result, :map)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:phase_id, :uuid, null: false)
      add(:actor_id, :uuid, null: false)
    end

    create unique_index(:actions, [:phase_id, :actor_id, :type],
             name: "actions_one_per_actor_per_phase_per_type_index"
           )

    alter table(:actions) do
      add(:target_id, :uuid, null: false)
    end

    create table(:games, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:join_code, :text, null: false)
      add(:timezone, :text, null: false, default: "Etc/UTC")
      add(:day_start, :time, null: false, default: fragment("'08:00:00'"))
      add(:day_end, :time, null: false, default: fragment("'20:00:00'"))
      add(:phase_ends_at, :utc_datetime_usec)
      add(:state, :text, null: false, default: "lobby")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :owner_id,
        references(:users,
          column: :id,
          name: "games_owner_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create unique_index(:games, [:join_code], name: "games_unique_join_code_index")

    create table(:phases, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:actions) do
      modify(
        :phase_id,
        references(:phases,
          column: :id,
          name: "actions_phase_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    alter table(:phases) do
      add(:kind, :text, null: false)
      add(:number, :bigint, null: false)

      add(:started_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:ended_at, :utc_datetime_usec)
      add(:summary, :map)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :game_id,
        references(:games,
          column: :id,
          name: "phases_game_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)
    end

    create unique_index(:phases, [:game_id, :number], name: "phases_unique_number_per_game_index")

    create table(:players, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:actions) do
      modify(
        :actor_id,
        references(:players,
          column: :id,
          name: "actions_actor_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :target_id,
        references(:players,
          column: :id,
          name: "actions_target_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    alter table(:players) do
      add(:role, :text)
      add(:alive, :boolean, null: false, default: true)

      add(:joined_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "players_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :game_id,
        references(:games,
          column: :id,
          name: "players_game_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)
    end

    create unique_index(:players, [:game_id, :user_id],
             name: "players_unique_user_per_game_index"
           )
  end

  def down do
    drop(constraint(:players, "players_game_id_fkey"))

    drop(constraint(:players, "players_user_id_fkey"))

    drop_if_exists(
      unique_index(:players, [:game_id, :user_id], name: "players_unique_user_per_game_index")
    )

    alter table(:players) do
      remove(:game_id)
      remove(:user_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:joined_at)
      remove(:alive)
      remove(:role)
    end

    drop(constraint(:actions, "actions_target_id_fkey"))

    drop(constraint(:actions, "actions_actor_id_fkey"))

    drop(constraint(:actions, "actions_phase_id_fkey"))

    alter table(:actions) do
      modify(:target_id, :uuid)
      modify(:actor_id, :uuid)
    end

    drop(table(:players))

    drop(constraint(:phases, "phases_game_id_fkey"))

    drop_if_exists(
      unique_index(:phases, [:game_id, :number], name: "phases_unique_number_per_game_index")
    )

    alter table(:phases) do
      remove(:game_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:summary)
      remove(:ended_at)
      remove(:started_at)
      remove(:number)
      remove(:kind)
    end

    alter table(:actions) do
      modify(:phase_id, :uuid)
    end

    drop(table(:phases))

    drop(constraint(:games, "games_owner_id_fkey"))

    drop_if_exists(unique_index(:games, [:join_code], name: "games_unique_join_code_index"))

    drop(table(:games))

    alter table(:actions) do
      remove(:target_id)
    end

    drop_if_exists(
      unique_index(:actions, [:phase_id, :actor_id, :type],
        name: "actions_one_per_actor_per_phase_per_type_index"
      )
    )

    drop(table(:actions))
  end
end
