defmodule WerewolfAsh.Repo.Migrations.AddAnnouncements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:announcements, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kind, :text, null: false)
      add(:announced_at, :utc_datetime_usec, null: false)
      add(:deaths, {:array, :map}, null: false, default: [])
      add(:winner, :text)
      add(:lynch_outcome, :text)
      add(:night_starting, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :game_id,
        references(:games,
          column: :id,
          name: "announcements_game_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)
    end

    alter table(:players) do
      add(:death_announced_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:players) do
      remove(:death_announced_at)
    end

    drop(constraint(:announcements, "announcements_game_id_fkey"))

    drop(table(:announcements))
  end
end
