defmodule WerewolfAsh.Repo.Migrations.ActionValidationsAndKill do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:actions, [:phase_id],
             name: "actions_one_kill_per_phase_index",
             where: "(type = 'kill')"
           )
  end

  def down do
    drop_if_exists(unique_index(:actions, [:phase_id], name: "actions_one_kill_per_phase_index"))
  end
end
