defmodule WerewolfAsh.Repo.Migrations.AddMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:channel, :text, null: false)
      add(:body, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :game_id,
        references(:games,
          column: :id,
          name: "messages_game_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)

      add(
        :author_id,
        references(:players,
          column: :id,
          name: "messages_author_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ), null: false)
    end
  end

  def down do
    drop(constraint(:messages, "messages_author_id_fkey"))

    drop(constraint(:messages, "messages_game_id_fkey"))

    drop(table(:messages))
  end
end
