defmodule WerewolfAsh.Repo.Migrations.AddHunterWindowToGames do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      add(:pending_hunter_id, :uuid)
      add(:hunter_deadline_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:games) do
      remove(:hunter_deadline_at)
      remove(:pending_hunter_id)
    end
  end
end
