defmodule WerewolfAsh.Repo.Migrations.AddGameWinner do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      add(:winner, :text)
    end
  end

  def down do
    alter table(:games) do
      remove(:winner)
    end
  end
end
