defmodule WerewolfAsh.Repo.Migrations.OwnerConfigurableGameSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      add(:role_distribution_mode, :text, null: false, default: "automatic")
      add(:manual_werewolf_count, :bigint)
      add(:seer_enabled, :boolean, null: false, default: true)
      add(:bodyguard_enabled, :boolean, null: false, default: true)
      add(:hunter_enabled, :boolean, null: false, default: true)
      add(:min_players, :bigint, null: false, default: 5)
      add(:max_players, :bigint)
    end
  end

  def down do
    alter table(:games) do
      remove(:max_players)
      remove(:min_players)
      remove(:hunter_enabled)
      remove(:bodyguard_enabled)
      remove(:seer_enabled)
      remove(:manual_werewolf_count)
      remove(:role_distribution_mode)
    end
  end
end
